// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

type Movie struct {
	MovieId     int    `json:"movieId"`
	Title       string `json:"title"`
	MtrcbRating string `json:"mtrcb_rating"`
	RunningTime string `json:"running_time"`
	In3d        bool   `json:"in3d"`
}

type Schedule struct {
	MovieId     int    `json:"movieId"`
	TheaterName string `json:"theaterName"`
	Date        string `json:"date"`
	Showtimes   string `json:"showtimes"`
}

type TheaterShowtimes struct {
	Status     bool   `json:"status"`
	Theater    string `json:"theater"`
	NowShowing string `json:"now_showing"`
	Schedules  string `json:"schedules"`
}
