version: 2
project_name: nowshowing-pp-cli
changelog:
  disable: true
builds:
  - id: nowshowing-pp-cli
    main: ./cmd/nowshowing-pp-cli
    binary: nowshowing-pp-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X nowshowing-pp-cli/internal/cli.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: nowshowing-pp-mcp
    main: ./cmd/nowshowing-pp-mcp
    binary: nowshowing-pp-mcp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
