// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"context"
	"crypto/tls"
	"fmt"
	"net"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// DeliverSink describes where command output should be routed when
// --deliver is set. Parsed from the sink specifier "scheme:target".
type DeliverSink struct {
	Scheme string
	Target string
}

// ParseDeliverSink parses a --deliver value. Supported schemes:
//
//	stdout          -> default, no redirection
//	file:<path>     -> write output atomically to <path>
//	webhook:<url>   -> POST output body to <url>
//
// Returns an error for unknown schemes with a message naming the
// supported set, so agents see a structured refusal rather than a
// silent misroute.
func ParseDeliverSink(spec string) (DeliverSink, error) {
	if spec == "" || spec == "stdout" {
		return DeliverSink{Scheme: "stdout"}, nil
	}
	idx := strings.Index(spec, ":")
	if idx == -1 {
		return DeliverSink{}, fmt.Errorf("unknown --deliver sink %q: expected scheme:target (supported: stdout, file:<path>, webhook:<url>)", spec)
	}
	scheme := spec[:idx]
	target := spec[idx+1:]
	switch scheme {
	case "file":
		if target == "" {
			return DeliverSink{}, fmt.Errorf("--deliver file:<path> requires a path")
		}
	case "webhook":
		if !strings.HasPrefix(target, "http://") && !strings.HasPrefix(target, "https://") {
			return DeliverSink{}, fmt.Errorf("--deliver webhook:<url> requires an http:// or https:// URL, got %q", target)
		}
	default:
		return DeliverSink{}, fmt.Errorf("unknown --deliver scheme %q (supported: stdout, file, webhook)", scheme)
	}
	return DeliverSink{Scheme: scheme, Target: target}, nil
}

// Deliver routes a captured output buffer to the configured sink. stdout
// is a no-op because the buffer has already been streamed to stdout via
// the MultiWriter set up in root.go.
func Deliver(sink DeliverSink, body []byte, compact bool) error {
	switch sink.Scheme {
	case "", "stdout":
		return nil
	case "file":
		return deliverFile(sink.Target, body)
	case "webhook":
		return deliverWebhook(sink.Target, body, compact)
	default:
		return fmt.Errorf("unsupported deliver sink %q", sink.Scheme)
	}
}

func deliverFile(path string, body []byte) error {
	// Atomic write: tmp + rename. Protects agents from seeing a partial
	// file if the process is interrupted mid-write.
	dir := filepath.Dir(path)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o700); err != nil {
			return fmt.Errorf("creating deliver dir: %w", err)
		}
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, body, 0o600); err != nil {
		return fmt.Errorf("writing deliver tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return fmt.Errorf("replacing deliver file: %w", err)
	}
	return nil
}

// deliverTLSConfig overrides the webhook client's TLS configuration.
// nil (default) uses Go's standard trust store — production behavior is
// unchanged. Tests set this to trust an httptest.NewTLSServer's
// self-signed certificate so the https code path can be exercised
// hermetically (see internal/cli/deliver_test.go).
var deliverTLSConfig *tls.Config

func deliverWebhook(target string, body []byte, compact bool) error {
	parsed, err := url.Parse(target)
	if err != nil {
		return fmt.Errorf("parsing webhook url: %w", err)
	}
	if parsed.Scheme == "http" {
		fmt.Fprintf(deliverStderr, "warning: --deliver webhook %s uses plain http; output (including any secrets in it) travels in cleartext — prefer https\n", target)
	}

	contentType := "application/json"
	if compact {
		contentType = "application/x-ndjson"
	}
	req, err := http.NewRequest(http.MethodPost, target, bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("building webhook request: %w", err)
	}
	req.Header.Set("Content-Type", contentType)
	req.Header.Set("User-Agent", "nowshowing-pp-cli/deliver")

	allowlist := parseAllowlist()
	client := &http.Client{
		Timeout: 30 * time.Second,
		CheckRedirect: func(req *http.Request, via []*http.Request) error {
			return fmt.Errorf("refusing to follow webhook redirect to %s: --deliver does not follow redirects; point it at the final URL directly", req.URL)
		},
		Transport: &http.Transport{
			DialContext:     safeDialContext(allowlist),
			TLSClientConfig: deliverTLSConfig,
		},
	}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("posting to webhook: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return fmt.Errorf("webhook returned %s", resp.Status)
	}
	return nil
}

// safeDialContext returns a Transport.DialContext hook that resolves the
// host itself and validates the SSRF denylist/allowlist policy against
// the resolved IP immediately before dialing it — closing the gap a
// request-build-time-only check would leave open (the transport would
// otherwise re-resolve the hostname at connect time, so a DNS answer
// that changes between check and connect — DNS rebinding — could slip
// an unvalidated IP through). Dialing the already-validated IP directly
// (instead of letting the transport re-resolve the hostname) means
// validation and connection always agree on the same address.
func safeDialContext(allowlist []string) func(ctx context.Context, network, addr string) (net.Conn, error) {
	dialer := &net.Dialer{Timeout: 10 * time.Second}
	resolver := net.DefaultResolver
	return func(ctx context.Context, network, addr string) (net.Conn, error) {
		host, port, err := net.SplitHostPort(addr)
		if err != nil {
			return nil, fmt.Errorf("parsing dial address %q: %w", addr, err)
		}
		if literal := net.ParseIP(host); literal != nil {
			if verr := validateResolvedIP(host, literal, allowlist); verr != nil {
				return nil, verr
			}
			return dialer.DialContext(ctx, network, addr)
		}
		ips, err := resolver.LookupIPAddr(ctx, host)
		if err != nil {
			return nil, fmt.Errorf("resolving webhook host %q: %w", host, err)
		}
		// Track validation refusals and dial failures separately so an
		// SSRF refusal is never masked by a later candidate's unrelated
		// dial error (e.g. connection refused) — an operator debugging a
		// blocked webhook should see the actionable "refusing ..."
		// message, not a generic network error, whenever every candidate
		// was in fact denylisted.
		var validationErr, dialErr error
		for _, ipAddr := range ips {
			if verr := validateResolvedIP(host, ipAddr.IP, allowlist); verr != nil {
				if validationErr == nil {
					validationErr = verr
				}
				continue
			}
			conn, derr := dialer.DialContext(ctx, network, net.JoinHostPort(ipAddr.IP.String(), port))
			if derr != nil {
				if dialErr == nil {
					dialErr = derr
				}
				continue
			}
			return conn, nil
		}
		if validationErr != nil {
			return nil, validationErr
		}
		if dialErr != nil {
			return nil, dialErr
		}
		return nil, fmt.Errorf("no usable address for webhook host %q", host)
	}
}
