// Copyright 2026 Nestor G Pestelos Jr and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package config

import (
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/pelletier/go-toml/v2"
	"github.com/ph-commons/nowshowing-pp-cli/internal/cliutil"
)

type Config struct {
	BaseURL       string            `toml:"base_url"`
	AuthHeaderVal string            `toml:"auth_header"`
	Headers       map[string]string `toml:"headers,omitempty"`
	AuthSource    string            `toml:"-"`
	Path          string            `toml:"-"`
	envOverrides  map[string]bool   `toml:"-"`
	fileConfig    *Config           `toml:"-"`
}

// allowedBaseURLHosts is the default host allowlist for the configured
// BaseURL (env NOWSHOWING_BASE_URL or config-file base_url). A shared-agent-
// host env (hostile NOWSHOWING_BASE_URL, or a config file an attacker can
// influence) must not be able to silently retarget the generated HTTP
// client's browser-UA traffic at an arbitrary or internal host. See issue
// #13 (M3, parent #6 security review).
//
// internal/httpx (issue #9 / PR #20, at time of writing not yet merged)
// maintains a parallel, larger allowedRedirectHosts list for a different
// subsystem entirely (redirect-hop gating for the hand-written ctc/popcorn/
// imdb source clients, which never route through internal/config or
// internal/client). Consolidating both into one shared allowlist package is
// a reasonable follow-up once #20 merges; kept separate here so this fix
// does not depend on an unmerged PR.
var allowedBaseURLHosts = map[string]struct{}{
	"clickthecity.com":     {},
	"www.clickthecity.com": {},
}

// allowCustomBaseURLEnvVar is the break-glass env var: with it set to "1", a
// NOWSHOWING_BASE_URL/config base_url pointing at a host outside
// allowedBaseURLHosts is accepted instead of Load() failing closed.
// Deliberately a new, dedicated var rather than reusing
// cliutil.IsVerifyEnv() (PRINTING_PRESS_VERIFY) — auto-bypassing on verify
// mode would let the exact same hostile-env actor this check defends
// against flip one more already-broadly-scoped var and defeat the
// allowlist for free.
//
// Residual limitation (accepted for this Medium-severity issue, not
// hidden): an attacker with full control over the process environment can
// set both NOWSHOWING_BASE_URL and this var in one shot. The fix raises the
// bar from "any single env var silently retargets" to "two specific env
// vars, or an explicit --allow-custom-base-url CLI flag" (the flag requires
// invocation-level control, which a pure env-var attacker does not
// automatically have) — it is not a claim of unbypassable isolation.
const allowCustomBaseURLEnvVar = "NOWSHOWING_ALLOW_CUSTOM_BASE_URL"

// isBaseURLHostAllowed reports whether rawURL's host is in
// allowedBaseURLHosts. Matching is an exact, case-insensitive string lookup
// on the parsed hostname (never strings.Contains/HasSuffix), so
// "notclickthecity.com", "clickthecity.com.evil.com", and
// "evilclickthecity.com" are all denied, and userinfo tricks like
// "clickthecity.com@evil.com" resolve to the real host ("evil.com") via
// net/url and are denied too. A trailing-dot FQDN ("clickthecity.com.") is
// DNS-equivalent to the bare form, so the trailing dot is trimmed before
// lookup to avoid a false-positive denial of legitimate traffic.
//
// An empty rawURL returns allowed=true — an unconfigured BaseURL is
// doctor's existing "not configured" case, not a host violation. A non-nil
// err (rawURL fails to parse — e.g. embedded whitespace or a malformed
// percent-escape) always means allowed=false: callers must fail closed on
// a parse error exactly as they would on a resolved-but-disallowed host,
// never treat "couldn't determine the host" as "so allow it."
func isBaseURLHostAllowed(rawURL string) (allowed bool, host string, err error) {
	if strings.TrimSpace(rawURL) == "" {
		return true, "", nil
	}
	u, err := url.Parse(rawURL)
	if err != nil {
		return false, "", err
	}
	host = strings.ToLower(strings.TrimSuffix(u.Hostname(), "."))
	_, ok := allowedBaseURLHosts[host]
	return ok, host, nil
}

// sortedAllowedBaseURLHosts returns allowedBaseURLHosts' keys in a stable
// (alphabetical) order for deterministic error-message formatting.
func sortedAllowedBaseURLHosts() []string {
	out := make([]string, 0, len(allowedBaseURLHosts))
	for h := range allowedBaseURLHosts {
		out = append(out, h)
	}
	sort.Strings(out)
	return out
}

// Load reads the config file (if any), applies env-var overrides, and
// validates the resulting BaseURL's host against allowedBaseURLHosts.
// allowCustomBaseURL is the CLI-flag break-glass (--allow-custom-base-url);
// the allowCustomBaseURLEnvVar env var is always also honored as a second,
// flag-independent break-glass (needed by callers with no flag surface,
// e.g. the MCP server). A disallowed host — from the default, the config
// file, or the env override — makes Load return a non-nil error and a nil
// *Config, so no caller ever constructs an HTTP client with a disallowed
// BaseURL.
func Load(configPath string, allowCustomBaseURL bool) (*Config, error) {
	cfg := &Config{
		BaseURL: "https://www.clickthecity.com",
	}

	// Resolve config path
	path, explicitConfigFile, err := resolveConfigPath(configPath)
	if err != nil {
		return nil, err
	}
	cfg.Path = path

	if explicitConfigFile {
		if err := readConfigFile(path, cfg, "config-kind path"); err != nil && !os.IsNotExist(err) {
			return nil, err
		}
	} else {
		legacyPath, err := LegacyConfigPath()
		if err != nil {
			return nil, err
		}
		data, sourcePath, err := cliutil.ReadFileWithLegacyFallback(path, legacyPath)
		if err != nil {
			if !os.IsNotExist(err) {
				return nil, err
			}
		} else {
			owner := "config-kind path"
			if sourcePath == legacyPath {
				owner = "legacy config path"
			}
			parsed := *cfg
			if err := parseConfigData(data, &parsed, sourcePath, owner); err != nil {
				if sourcePath == legacyPath {
					fmt.Fprintf(os.Stderr, "warning: legacy config parse skipped for %s: %v\n", sourcePath, err)
				} else {
					return nil, err
				}
			} else {
				*cfg = parsed
			}
		}
	}
	cfg.Path = path

	cfg.snapshotFileConfig()

	// Env var overrides

	// Base URL override (used by printing-press verify to point at mock/test
	// servers). As of issue #13 (M3), the resulting BaseURL is gated by the
	// host-allowlist check below — a verify/mock flow pointing this at a
	// non-allowlisted host (e.g. an httptest.Server) must also set
	// NOWSHOWING_ALLOW_CUSTOM_BASE_URL=1 to avoid the fail-closed error.
	if v := os.Getenv("NOWSHOWING_BASE_URL"); v != "" {
		cfg.BaseURL = v
	}

	// Host allowlist gate. Runs last, against the fully-overlaid BaseURL
	// (default -> config file -> env override), so a disallowed host from
	// any of those three sources is caught here, not just the env-var case.
	// See allowedBaseURLHosts and allowCustomBaseURLEnvVar above (issue #13,
	// M3).
	allowed, host, perr := isBaseURLHostAllowed(cfg.BaseURL)
	if perr != nil {
		return nil, fmt.Errorf("parsing base_url %q: %w", cfg.BaseURL, perr)
	}
	if !allowed {
		breakGlass := allowCustomBaseURL || os.Getenv(allowCustomBaseURLEnvVar) == "1"
		if !breakGlass {
			return nil, fmt.Errorf(
				"base_url host %q is not in the allowlist (%s); pass --allow-custom-base-url or set %s=1 to override",
				host, strings.Join(sortedAllowedBaseURLHosts(), ", "), allowCustomBaseURLEnvVar,
			)
		}
	}

	return cfg, nil
}

func resolveConfigPath(configPath string) (string, bool, error) {
	if strings.TrimSpace(configPath) != "" {
		return configPath, true, nil
	}
	if path := os.Getenv("NOWSHOWING_CONFIG"); path != "" {
		return path, true, nil
	}
	dir, err := cliutil.ConfigDir()
	if err != nil {
		return "", false, err
	}
	return filepath.Join(dir, "config.toml"), false, nil
}

func LegacyConfigPath() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve legacy config path: %w", err)
	}
	return filepath.Join(home, ".config", "nowshowing-pp-cli", "config.toml"), nil
}

func readConfigFile(path string, cfg *Config, owner string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return parseConfigData(data, cfg, path, owner)
}

func parseConfigData(data []byte, cfg *Config, path string, owner string) error {
	if err := toml.Unmarshal(data, cfg); err != nil {
		return fmt.Errorf("parsing %s %s: %w", owner, path, err)
	}
	return nil
}

func (c *Config) AuthHeader() string {
	if c.AuthHeaderVal != "" {
		return c.AuthHeaderVal
	}
	return ""
}

func applyAuthFormat(format string, replacements map[string]string) string {
	if format == "" {
		return ""
	}
	for key, value := range replacements {
		format = strings.ReplaceAll(format, "{"+key+"}", value)
	}
	if strings.Contains(format, "{") {
		return ""
	}
	return format
}

func (c *Config) markEnvOverride(field string) {
	if c.envOverrides == nil {
		c.envOverrides = map[string]bool{}
	}
	c.envOverrides[field] = true
}

// cloneStringMap returns an independent copy of m (nil stays nil). The fileConfig
// snapshot must not share reference-type map fields (such as Headers) with the
// live config, or a later mutation to one would silently track in the other.
func cloneStringMap(m map[string]string) map[string]string {
	if m == nil {
		return nil
	}
	out := make(map[string]string, len(m))
	for k, v := range m {
		out[k] = v
	}
	return out
}

func (c *Config) snapshotFileConfig() {
	snapshot := *c
	snapshot.envOverrides = nil
	snapshot.fileConfig = nil
	// *c is a shallow copy: map fields are reference types, so the snapshot would
	// share them with c and silently track later mutations, defeating the
	// isolation this snapshot exists to provide. Clone them.
	snapshot.Headers = cloneStringMap(c.Headers)
	c.fileConfig = &snapshot
}

func (c *Config) configForSave() Config {
	out := *c
	if c.fileConfig != nil {
	}
	out.envOverrides = nil
	out.fileConfig = nil
	return out
}

func (c *Config) updateFileConfigField(field string) {
	if c.fileConfig == nil || c.envOverrides[field] {
		return
	}
	switch field {
	case "AuthHeaderVal":
		c.fileConfig.AuthHeaderVal = c.AuthHeaderVal
	}
}

func (c *Config) save() error {
	persisted := c.configForSave()
	var persist any = persisted
	data, err := toml.Marshal(persist)
	if err != nil {
		return fmt.Errorf("marshaling config: %w", err)
	}
	if err := cliutil.AtomicWritePrivateFile(c.Path, data, 0o600, 0o700); err != nil {
		return err
	}
	c.fileConfig = &persisted
	c.fileConfig.envOverrides = nil
	c.fileConfig.fileConfig = nil
	// persisted shares its map fields with c (configForSave shallow-copies *c),
	// so isolate the stored fileConfig the same way snapshotFileConfig does;
	// otherwise later mutations to c's maps leak into the on-disk snapshot.
	c.fileConfig.Headers = cloneStringMap(c.fileConfig.Headers)
	return nil
}

// Ensure strings import is used
var _ = strings.ReplaceAll
